quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_j3rEvXm5WtRT
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-empty-glitter-ackm9l8j-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true